<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                      ->prependStylesheet($this->basePath() . '/css/main.css');
        echo $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
        ?>
        <title>Pokedex</title>
    </head>
    <body>
        <div id="container">
            <div id="header">
                <div class="content" style="margin-top: 10px;">
                    <h1>
                        <a href="<?php echo $this->url('home');?>">
                            <img class="center" src="<?php echo $this->basePath();?>/images/logo-go.png" height="150px" alt="Pokemon Board" />
                        </a>
                    </h1>
                </div>
            </div>
            <div id="content">
                <div class="content">
                    <?php echo $this->content; ?>
                </div>
            </div>
            <div id="footer">   
            </div>
        </div>
    </body>
</html>

