<?php
    use \Pokedex\Filter\Slugify as Slugify;

    $slug = new Slugify();
?>
<div class="container">
    <table>
        <?php if (isset($this->pokemons)) :?>
        <?php foreach($this->pokemons as $test => $pokemon): ?>
                <tbody>
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </tbody>
            <div class="col-xs-12 col-md-4 col-md-offset-4">
                    <img src="<?php echo $this->basePath() . "/pokemon_img/".$pokemon['avatar']?>" height="210px"/><br>
                <a href="<?php echo $this->url('home/action', array('action' => 'get', 'id' => $pokemon['id']), null, false);?>">
                <span><?php echo $pokemon['name'] ?></span> - <span>#<?php echo $pokemon['national_id']?></span></a><br>
                    <span><?php echo $this->types[$pokemon['type_principal'] - 1]['label'] ?>
                    <?php if (isset($pokemon['type_secondaire'])) :?>
                        - <span><?php echo $this->types[$pokemon['type_secondaire'] - 1]['label'] ?>
                    <?php endif?>
            </div>
        <?php endforeach;?>
            <?php else :?>
                <div class="col-xs-12 col-md-4 col-md-offset-4">
                    Veuillez ajouter un pokemon dans la base de données
                </div>
            <?php endif;?>
    </table>
</div>
