<?php
$this->headTitle($this->pokemon->name);

?>

<h1 style="text-align: center;"><?php echo $this->escapeHtml($this->pokemon->name); ?> - #<?php echo $this->pokemon->national_id ?>  </h1>

<div class="container-fluid" style=" margin-bottom: 20px;">
    <div id="pokedex">
        <div id="left">
            <div id="logo"></div>
            <div id="bg_curve1_left"></div>
            <div id="bg_curve2_left"></div>
            <div id="curve1_left">
                <div id="buttonGlass">
                    <div id="reflect"> </div>
                </div>
                <div id="miniButtonGlass1"></div>
                <div id="miniButtonGlass2"></div>
                <div id="miniButtonGlass3"></div>
            </div>
            <div id="curve2_left">
                <div id="junction">
                    <div id="junction1"></div>
                    <div id="junction2"></div>
                </div>
            </div>
            <div id="screen">
                <div id="topPicture">
                    <div id="buttontopPicture1"></div>
                    <div id="buttontopPicture2"></div>
                </div>
                <div id="picture">
                    <img src="<?php echo $this->basePath()."/pokemon_img/".$this->pokemon->avatar;?>" alt="<?php echo $this->pokemon->name?>" height="170" />
                </div>
                <div id="buttonbottomPicture"></div>
                <div id="speakers">
                    <div class="sp"></div>
                    <div class="sp"></div>
                    <div class="sp"></div>
                    <div class="sp"></div>
                </div>
            </div>
            <div id="bigbluebutton"></div>
            <div id="barbutton1"></div>
            <div id="barbutton2"></div>
            <div id="cross">
                <div id="leftcross">
                    <?php if ($this->pokemon->id >= 2) :?>
                        <a href="<?php echo $this->url('home/action',
                            array('action' => 'get', 'id' => $this->pokemon->id - 1), null, false);?>">
                            <div id="leftT"></div>
                        </a>
                    <?php else: ?>
                        <div id="leftT"></div>
                    <?php endif; ?>
                </div>
                <div id="topcross">
                    <div id="upT"></div>
                </div>
                <div id="rightcross">

                </div>
                <div id="midcross">
                    <div id="midCircle"></div>
                </div>
                <div id="botcross">
                    <div id="downT"></div>
                </div>
            </div>
        </div>
        <div id="right">
            <div id="stats">
                <strong>Nom : </strong><?php echo $this->pokemon->name ?><br/>
                <strong>Type Principal :</strong> <?php echo $this->types[$this->pokemon->type_principal - 1]['label'] ?><br/>
                <?php if ($this->pokemon->type_secondaire != null) :?>
                    <strong>Type Secondaire :</strong> <?php echo $this->types[$this->pokemon->type_secondaire - 1]['label'] ?><br/>
                <?php endif ?><br/>
                <strong><?php echo $this->pokemon->description ?></strong><br/>
            </div>
            <div id="blueButtons2">
                <div class="blueButton"></div>
                <div class="blueButton"></div>
                <div class="blueButton"></div>
                <div class="blueButton"></div>
                <div class="blueButton"></div>
            </div>
            <div id="miniButtonGlass4"></div>
            <div id="miniButtonGlass5"></div>
            <div id="barbutton3"></div>
            <div id="barbutton4"></div>
            <div id="yellowBox1"></div>
            <div id="yellowBox2"></div>
            <div id="bg_curve1_right"></div>
            <div id="bg_curve2_right"></div>
            <div id="curve1_right"></div>
            <div id="curve2_right"></div>
        </div>
    </div><br/>
</div> <br />

<div class="container-fluid" >
    <h1 style="text-align: center;">Evolution de <?php echo $this->escapeHtml($this->pokemon->name); ?> </h1>
    <div class="col-xs-0 col-sm-0 col-md-1 col-lg-1" style="
">
    </div>
    <?php foreach($this->evolutions as $evolution): ?>
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3" style="
    background-color: white;
        box-sizing: border-box;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    border: 1px solid #3F3D47;
    text-align: center;
">
            <img src="<?php echo $this->basePath() . "/pokemon_img/".$evolution->avatar?>" height="210px"/><br>
            <a href="<?php echo $this->url('home/action', array('action' => 'get', 'id' => $evolution->id), null, false);?>">
                <span><?php echo $evolution->name ?></span> - <span>#<?php echo $evolution->national_id?></span></a><br>
            <span><?php echo $this->types[$evolution->type_principal - 1]['label'] ?>
                <?php if (isset($evolution->type_secondaire)) :?>
                - <?php echo $this->types[$evolution->type_secondaire - 1]['label'] ?></span>
            <?php endif?>
        </div>
    <?php endforeach;?>
</div><br/>
