<?php
    use \Pokedex\Filter\Slugify as Slugify;

    $slug = new Slugify();
?>
<div class="container-fluid">
        <div class="row">
            <?php if (isset($this->pokemons)) :?>
            <?php foreach($this->pokemons as $test => $pokemon): ?>
            <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3" style="
    background-color: white;
        box-sizing: border-box;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    border: 1px solid #3F3D47;
    text-align: center;
">
                <a href="<?php echo $this->url('zfcadmin/pokemon/action', array('action' => 'get', 'id' => $pokemon['id']), null, false);?>">
                <span><?php echo $pokemon['name'] ?></span> - <span>N°<?php echo $pokemon['national_id']?></span></a><br>
                    <span><?php echo $this->types[$pokemon['type_principal'] - 1]['label'] ?>
                    <?php if (isset($pokemon['type_secondaire'])) :?>
                        - <?php echo $this->types[$pokemon['type_secondaire'] - 1]['label'] ?></span>
                    <?php endif?>
                <span><?php
                    $urlEdit = $this->url('zfcadmin/pokemon/action',array('action' => 'edit', 'id' => $pokemon['id']), null, false);
                    $urlDelete = $this->url('zfcadmin/pokemon/action', array('action' => 'delete', 'id' => $pokemon['id']), null, false);
                    ?>
                    <a href="<?php echo $urlEdit;?>"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        <a href="<?php echo $urlDelete;?>"><i class="fa fa-trash-o" aria-hidden="true"></i></a></span>
            </div>
        <?php endforeach;?>
            <?php else :?>
                <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3" style="
    background-color: white;
        box-sizing: border-box;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    border: 1px solid #3F3D47;
    text-align: center;
">
                    Aucun pokémon n'existe en base !
                </div>
            <?php endif;?>

    </div>
</div>
